name: se_project_food
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  clipboard: ^0.1.3
  email_validator: ^2.1.17
  video_player: ^2.7.2

  #Firebase Dependencies
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.2

  #Common Dependencies
  get: ^4.6.5
  image_picker: ^1.0.0
  file_picker: ^5.3.2
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.14

  #Decoration Dependencies
  simple_circular_progress_bar: ^1.0.2
  flare_flutter: ^3.0.2
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  curved_navigation_bar: ^1.0.3
  flutter_svg: ^2.0.7
  another_carousel_pro: ^1.0.0

  
  fluttertoast: ^8.0.7
  dropdown_button2: ^2.3.4
  carousel_slider: ^4.0.0
  page_transition: ^2.0.9
  shimmer: ^3.0.0
  flutter_speed_dial: ^7.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_slidable: ^0.6.0
  awesome_dialog: ^3.1.0
  intl: ^0.18.1



  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - images/logo.png
    - images/search-svgrepo-com.svg
    - images/food.jpg
    - images/james-person-1.jpg
    - images/0star.png
    - images/1star.png
    - images/2star.png
    - images/3star.png
    - images/4star.png
    - images/5star.png
    - images/noimage.png
  #   - images/a_dot_ham.jpeg
    - images/nation/thai.png
    - images/nation/usa.png
    - images/nation/english.png
    - images/nation/france.png
    - images/nation/germany.png
    - images/nation/japan.jpg
    - images/nation/italy.png
    - images/nation/india.png
    - images/nation/spain.png
    - images/nation/korea.png
    - images/nation/china.jpg
    - images/nation/nations.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
